# Generated by Django 5.0.6 on 2024-06-09 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='u_message',
            field=models.TextField(blank=True, max_length=50000, null=True),
        ),
    ]
