# Generated by Django 5.0.6 on 2024-06-09 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_alter_client_name_clientextended'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientExtended',
        ),
    ]
